import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Self-Made-Blog-Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        
        
        
        
        
        
      <div>
        <ul className="flex justify-center gap-4 p-4 bg-gray-200">
          <Link className="bg-amber-500 p-3 rounded-lg" href="/">Home</Link>
          <Link className="bg-amber-500 p-3 rounded-lg" href="/users">Users</Link>
        </ul>
      </div>
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        {children}</body>
    </html>
  );
}
